from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np


@dataclass
class PipelineState:
    """
    Shared state object passed between all debug pipeline steps.

    This stores both long-lived backend objects and intermediate results
    generated by the individual steps.
    """

    # Core backend / config
    env: Optional[Any] = None
    config: Optional[Any] = None

    # Routing / board related data
    routing: Optional[List[int]] = None
    clips: Optional[Any] = None
    crossing_fixture_id_list: Optional[List[int]] = None

    # Images for display
    rgb_image: Optional[np.ndarray] = None
    routing_overlay: Optional[np.ndarray] = None
    trace_overlay: Optional[np.ndarray] = None
    grasp_overlay: Optional[np.ndarray] = None
    # Camera-based first-route preview (plan_first_route); shown above trace_overlay.
    first_route_overlay: Optional[np.ndarray] = None
    # Set by execute_first_route after a successful motion.
    first_route_executed: bool = False

    # Perception results
    path_in_pixels: Optional[np.ndarray] = None
    path_in_world: Optional[np.ndarray] = None
    cable_orientations: Optional[np.ndarray] = None
    loaded_trace_path: Optional[str] = None

    # Grasp preview
    grasp_preview: Optional[Dict[str, Any]] = None

    # Robot motion
    robot_target_sent: bool = False
    # Handover: orientation 3x3 world after handover_fine_orient; used by handover_move_exchange.
    handover_tcp_rotation_world: Optional[np.ndarray] = None
    # TCP world position (3,) after handover_move_exchange — used by dual-arm presentation steps.
    handover_carrier_tcp_world: Optional[np.ndarray] = None
    handover_fine_orient_done: bool = False
    handover_exchange_done: bool = False
    handover_repark_done: bool = False  # True after exchange move (compat. with old name)
    present_cable_vertical_done: bool = False
    second_arm_side_approach_done: bool = False

    # Metadata / logging
    logs: List[str] = field(default_factory=list)
    finished_steps: List[str] = field(default_factory=list)

    def log(self, message: str) -> None:
        """
        Store a log message in the shared state.
        """
        self.logs.append(message)

    def reset_runtime_data(self) -> None:
        """
        Reset only intermediate runtime data while keeping the object itself alive.
        Useful for GUI reset flows.
        """
        self.routing = None
        self.clips = None
        self.crossing_fixture_id_list = None

        self.rgb_image = None
        self.routing_overlay = None
        self.trace_overlay = None
        self.grasp_overlay = None
        self.first_route_overlay = None
        self.first_route_executed = False

        self.path_in_pixels = None
        self.path_in_world = None
        self.cable_orientations = None
        self.loaded_trace_path = None

        self.grasp_preview = None

        self.handover_tcp_rotation_world = None
        self.handover_carrier_tcp_world = None
        self.handover_fine_orient_done = False
        self.handover_exchange_done = False
        self.handover_repark_done = False
        self.present_cable_vertical_done = False
        self.second_arm_side_approach_done = False

        self.logs.clear()
        self.finished_steps.clear()
