from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np


@dataclass
class PipelineState:
    """
    Shared state object passed between all debug pipeline steps.

    This stores both long-lived backend objects and intermediate results
    generated by the individual steps.
    """

    # Core backend / config
    env: Optional[Any] = None
    config: Optional[Any] = None

    # Routing / board related data
    routing: Optional[List[int]] = None
    clips: Optional[Any] = None
    crossing_fixture_id_list: Optional[List[int]] = None

    # Images for display
    rgb_image: Optional[np.ndarray] = None
    routing_overlay: Optional[np.ndarray] = None
    trace_overlay: Optional[np.ndarray] = None
    grasp_overlay: Optional[np.ndarray] = None

    # Perception results
    path_in_pixels: Optional[np.ndarray] = None
    path_in_world: Optional[np.ndarray] = None
    cable_orientations: Optional[np.ndarray] = None

    # Grasp preview
    grasp_preview: Optional[Dict[str, Any]] = None

    # Metadata / logging
    logs: List[str] = field(default_factory=list)
    finished_steps: List[str] = field(default_factory=list)

    def log(self, message: str) -> None:
        """
        Store a log message in the shared state.
        """
        self.logs.append(message)

    def reset_runtime_data(self) -> None:
        """
        Reset only intermediate runtime data while keeping the object itself alive.
        Useful for GUI reset flows.
        """
        self.routing = None
        self.clips = None
        self.crossing_fixture_id_list = None

        self.rgb_image = None
        self.routing_overlay = None
        self.trace_overlay = None
        self.grasp_overlay = None

        self.path_in_pixels = None
        self.path_in_world = None
        self.cable_orientations = None

        self.grasp_preview = None

        self.logs.clear()
        self.finished_steps.clear()
